### ISSUE TITLE
only test

### ISSUE THREAD

**Issue by wwfcnu** [LAION-AI/CLAP#110]
When I don't train, just test based on a pretrained checkpoint, I use the following script：
```
srun --comment clap --cpu_bind=v --accel-bind=gn python -m laion_clap.training.main \
    --save-frequency 5 \
    --save-top-performance 3 \
    --save-most-recent \
    --dataset-type="webdataset" \
    --precision="fp32" \
    --batch-size=256 \
    --lr=1e-5 \
    --wd=0.0 \
    --epochs=0 \
    --workers=6 \
    --use-bn-sync \
    --amodel HTSAT-base \
    --tmodel chineseclip \
    --warmup 3200 \
    --freeze-audio \
    --datasetnames "clotho" "audiocaps" "sounddesc" \
    --datasetinfos "train" "unbalanced_train" \
    --logs "clap_test_logs" \
    --seed 3407 \
    --datasetpath "/home/wangweifei/repository/wair/webdataset_tar/chinese" \
    --gather-with-grad \
    --optimizer "adam" \
    --data-filling "repeatpad" \
    --data-truncating "rand_trunc" \
    --pretrained '/home/tangshuai/repository/audio_generation/CLAP/experiment_scripts/clap_logs/2023_07_12-19_51_52-model_HTSAT-base-lr_1e-05-b_256-j_6-p_fp32/checkpoints/epoch_90.pt'


运行这段脚本，日志中显示的报错信息是
```
Traceback (most recent call last):
  File "/home/tangshuai/anaconda3/envs/audioldm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tangshuai/anaconda3/envs/audioldm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tangshuai/repository/audio_generation/CLAP/src/laion_clap/training/main.py", line 609, in <module>
    main()
  File "/home/tangshuai/repository/audio_generation/CLAP/src/laion_clap/training/main.py", line 333, in main
    total_steps = data["train"].dataloader.num_batches * args.epochs
KeyError: 'train'

**Comment by RetroCirce** [comment]
You can use our [pip library](https://pypi.org/project/laion-clap/) to infer or test the data. Or you can refer to [this code](https://github.com/LAION-AI/CLAP/tree/main/src/laion_clap/evaluate) and [this script](https://github.com/LAION-AI/CLAP/blob/main/experiment_scripts/zeroshot_esc50.sh) to build your own testing.
