### ISSUE TITLE
`pip install laion-clap` fails

### ISSUE THREAD

**Issue by loudar** [LAION-AI/CLAP#155]
```
Collecting laion-clap
  Downloading laion_clap-1.1.4-py3-none-any.whl.metadata (26 kB)
Collecting numpy==1.23.5 (from laion-clap)
  Downloading numpy-1.23.5.tar.gz (10.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 11.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__       
    return any(self)
           ^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>      
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built     
    candidate = func()
                ^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 185, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 231, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__
    super().__init__(
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement        
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata      
    self._install_build_reqs(finder)
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\utils\misc.py", line 709, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel      
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend   
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\AlexanderFritsch\AppData\Local\Temp\pip-build-env-g9n7e2p3\overlay\Lib\site-packages\setuptools\__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'

(.venv) PS C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding> pip install distutils
ERROR: Could not find a version that satisfies the requirement distutils (from versions: none)
ERROR: No matching distribution found for distutils
(.venv) PS C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding> pip install laion-clap
Collecting laion-clap
  Using cached laion_clap-1.1.4-py3-none-any.whl.metadata (26 kB)
Collecting numpy==1.23.5 (from laion-clap)
  Using cached numpy-1.23.5.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__       
    return any(self)
           ^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>      
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built     
    candidate = func()
                ^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 185, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 231, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__
    super().__init__(
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement        
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata      
    self._install_build_reqs(finder)
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_internal\utils\misc.py", line 709, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel      
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\Users\AlexanderFritsch\PycharmProjects\audio-embedding\audio-embedding\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend   
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlexanderFritsch\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\AlexanderFritsch\AppData\Local\Temp\pip-build-env-r1ee76zf\overlay\Lib\site-packages\setuptools\__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
```

**Comment by Wayne-dot** [comment]
For the error message
"""
pip install distutils
ERROR: Could not find a version that satisfies the requirement distutils (from versions: none)
ERROR: No matching distribution found for distutils
"""

I found [this link ](https://stackoverflow.com/questions/32302379/could-not-find-a-version-that-satisfies-the-requirement-package) that is related to your error

Sometimes specific python version is required, from [this link](https://stackoverflow.com/questions/55749206/modulenotfounderror-no-module-named-distutils-core), so double check all your dependencies version
